#!/bin/sh

FNAME=$1

TEMP=`date +%Y-%m-%d`/`uuidgen`

ssh fsck.com "cd ~/public_html/ && \
mkdir -p tmp/$TEMP && \
chmod o-r tmp/$TEMP
" && \
scp "$FNAME" "fsck.com:public_html/tmp/$TEMP" >/dev/null && \
echo "http://fsck.com/~jesse/tmp/${TEMP}/`basename $FNAME`" 
if [ "fnord$DISPLAY" != "fnord" ]; then
	echo "http://fsck.com/~jesse/tmp/${TEMP}/`basename $FNAME`" |pbcopy
fi
